trigger: 
  branches:
   include:
     - uat
     - UAT
  paths:
   include:
     - force-app/*

# Pull Request Trigger
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: uat

stages:
  - stage: SFDeployANDValidate
    jobs:
      - job: SFDeployANDValidate
      - template: ../ado_templates/template.yml
        parameters:
          SF_USER_NAME: $(SF_USER_NAME)
          SF_ALIAS: $(SF_ALIAS)
          SF_CLIENT_ID: $(SF_CLIENT_ID)
          SF_INSTANCE_URL: $(SF_INSTANCE_URL)
          SECURE_FILE_NAME: 'server-uat.key'
          PR_MERGED: true