# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
 branches:
  include:
    - main
    - master

pool:
  vmImage: ubuntu-latest

stages:

  - stage: ReadPRBody
    jobs:
    - job: FetchPRDetails
      steps:
      
      # Fetch PR Details using InvokeRESTAPI
      - task: InvokeRESTAPI@1
        displayName: "Fetch PR Details"
        inputs:
          connectionType: 'ConnectedServiceName'
          serviceConnection: 'AzureDevOpsServiceConnection'  # Replace with your service connection name
          method: 'GET'
          urlSuffix: '/_apis/git/repositories/$(Build.Repository.Name)/pullrequests/$(System.PullRequest.PullRequestId)?api-version=7.1-preview.1'
          waitForCompletion: "true"
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
        continueOnError: false

      # Save PR Body to a File
      - task: PowerShell@2
        displayName: "Save PR Body to File"
        inputs:
          targetType: 'inline'
          script: |
            $response = "$(InvokeRESTAPI.responseBody)"
            $json = $response | ConvertFrom-Json
            $prBody = $json.description
            $filePath = "$(Build.ArtifactStagingDirectory)/PR_Body.txt"
            $prBody | Out-File -FilePath $filePath -Encoding utf8
            Write-Host "##vso[task.setvariable variable=PR_BODY_FILE]$filePath"
            Write-Host "PR Body saved to: $filePath"

      # Publish File as an Artifact (Optional)
      - task: PublishBuildArtifacts@1
        displayName: "Publish PR Body File"
        inputs:
          pathToPublish: "$(Build.ArtifactStagingDirectory)/PR_Body.txt"
          artifactName: "PRDetails"

      # Read and Print PR Body in the Next Step
      - task: PowerShell@2
        displayName: "Read & Print PR Body"
        inputs:
          targetType: 'inline'
          script: |
            $filePath = "$(PR_BODY_FILE)"
            if (Test-Path $filePath) {
                $prBody = Get-Content -Path $filePath -Raw
                Write-Host "Pull Request Body:"
                Write-Host "---------------------"
                Write-Host $prBody
            } else {
                Write-Host "PR Body file not found."
            }

  - stage: SFDeployANDValidate
    jobs:
      - job: SFValidate
        steps:
          - script: npm install -g @salesforce/cli
            displayName: Install Salesforce CI
          - script: sf --version
            displayName: Verify CLI Installation 
          - script: |
              echo 'y' | sf plugins install sfdx-git-delta
              sf plugins install @salesforce/sfdx-scanner
            displayName: Install Required Plugins
      - job: SFDeploy
        steps:
          - script: echo "SFBuild is running"
            displayName: Single Line Script
          - script: |
              echo "Multiple line 1"
              echo "Multiple line 2"
            displayName: MultiLine Script
